### ISSUE TITLE
something uncertain

### ISSUE THREAD

**Issue by e66** [TECREA/QuarkTS#13]
Dear friend：
        Thank you for the last help， what about the RAM, today i will have a test on my stc15f2k60s2 mcu -_-!

Best wishes to you and your family!

**Comment by kmilo17pet** [comment]
hi e66,
That depends of how many task and OS-features(state-machines, queues, cli, etc..) you will use in your application. Its really hard to catch this information, there are to many variables, like the core architecture, compiler, optimization options and the application itself, that's  why you cant get this information from others OS.
In a really simple environment, on a 16bit MCU, and running 2 tasks it cant take from 250 to 300bytes.
Please do not use this GitHub section to answer concerns. This section is only for bug-tracking, report portability issues and requesting new features.
You can write to <kmilo17pet@gmail.com> if you have more concerns.
Best regards.
