### ISSUE TITLE
#define Q_QUEUES   ( 0 )   // Does not compile

### ISSUE THREAD

**Issue by dashkova** [TECREA/QuarkTS#18]
Hi!
If I write Q_QUEUES (0) in config.h, then I get an error:

> Severity	Code	Description	Project	File	Line
Error		'qQUEUE_COUNT' undeclared (first use in this function)	Blink_QuarkTS	 os\qkernel.c	490

**Comment by kmilo17pet** [comment]
hi @dashkova, already fixed in the last commit.  Thanks for reporting.
