### ISSUE TITLE
#define Q_SETUP_TIME_CANONICAL ( 1 ) // Error

### ISSUE THREAD

**Issue by dashkova** [TECREA/QuarkTS#19]
Hi!
If I write Q_SETUP_TIME_CANONICAL (1) in config.h, then I get an error:

> Severity	Code	Description	Project	File	Line
Error		undefined reference to `qClock_InternalTick'	Blink_QuarkTS	Blink_QuarkTS\os\qclock.c	47

Thanks!

**Comment by kmilo17pet** [comment]
fixed!
