### ISSUE TITLE
Crash while using Priority-Queue

### ISSUE THREAD

**Issue by HpLightcorner** [TECREA/QuarkTS#4]
Hey QuarkTS-Team,

COMPILER: MSVC, CLANG, Aurix-Tasking/Infineon Free-Toolchain
ISSUE: Crash in Kernel when using Priority-Queue (qTaskQueueNotification)

Solution:
https://github.com/TECREA/QuarkTS/blob/ca9a3116e75ead6c0e0fb691aadcc765fef49f3c/src/os/qkernel.c#L208

Tail is equal NULL, isn't it? Hence the statement should be:
`if( NULL == kernel.QueueStack[i].Task )`

I am still not through the complete Quark-TS Magic, but changing the Line to equals-NULL check fixes the issue for me.

Thanks in advance!

**Comment by HpLightcorner** [comment]
Please check if it is indeed a Bug - I can make a Pull-Request if you want

**Comment by kmilo17pet** [comment]
how!, the error happened in this [commit](https://github.com/TECREA/QuarkTS/commit/085746f9ff36f5316ff0cd59f78c3fd4e3afa284)  and was never detected in subsequent tests. 
That must be fixed right now!
Thanks!!

**Comment by HpLightcorner** [comment]
That was fast - thanks for your quick reaction. I will try to further contribute!
