### ISSUE TITLE
Move qconfig.h away from standard-sources

### ISSUE THREAD

**Issue by HpLightcorner** [TECREA/QuarkTS#6]
Hey,

Again just a minor suggestion:
The qconfig.h file might me specific for each user - as in my case, I have deactivated a lot of features. So every time I want to stay up to date with the latest commits, I have to remove/change the qconfig.h file.

I think I would be a good idea to move it from src/os/include to maybe just src/ and let the build system ensure that the qconfig.h file is present on the include paths.

So the users can directly pull the src/os/ foulder having their specific qconfig.h on another path where all their global configs may life.

Hopefully my suggestions is clear.

Kind regards

**Comment by kmilo17pet** [comment]
advice accepted, thanks bro!.
